apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea-deployment
  labels:
    app: gitea
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitea
  template:
    metadata:
      labels:
        app: gitea
    spec:
      containers:
      - name: gitea
        image: anicnkakb/gitea2:latest
        ports:
        - containerPort: 3000
        env:
        - name: USER_NAME
          valueFrom:
            secretKeyRef:
              name: mariadb-secret
              key: mariadb-user
        - name: USER_PWD
          valueFrom:
            secretKeyRef:
              name: mariadb-secret
              key: mariadb-password
        - name: DB_URL
          valueFrom:
            configMapKeyRef:
              name: mariadb-config
              key: mariadb-url
